### PR TITLE
Changes from John

### PR DESCRIPTION
**Pull request by johnmoen**
I'd like you to consider this..

### CODE REVIEW

**Comment by PeterBell** [comment]
Hmmm, not bad - what does anyone else think?

**Comment by PeterBell** [comment]
Looks great - :+1: - let's :ship: it

**Comment by PeterBell** [comment]
Stick a :fork_and_knife: in it

**Comment by greenehouse** [comment]
Thanks for the contribution...

**Comment by bacchustiger** [comment]
:+1:

**Comment by githubclass** [comment]
:-1:

**Comment by certify** [comment]
I'm going to over rule and say :+1:

**Pull request merged**
